#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=0

start_service() {
	/usr/bin/p2modemctl connect
}

stop_service() {
	/usr/bin/p2modemctl disconnect
}

restart() {
	stop_service
	sleep 2
	start_service
}
