#!/bin/sh /etc/rc.common

START=95
STOP=10

start_service() {
	/usr/bin/p2modemctl start >/tmp/p2modem-start.log 2>&1 &
}

stop_service() {
	/usr/bin/p2modemctl disconnect >/tmp/p2modem-stop.log 2>&1 || true
}
