include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-p2modem
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Cudy P2 modem control
LUCI_DEPENDS:=+luci-base +luci-mod-network +luci-lib-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
